# Generated by Django 5.0.4 on 2024-04-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_company_alter_invitation_id_cargo_user_companny_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("admin", "admin"),
                    ("trucker", "trucker"),
                ],
                default="trucker",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("admin", "admin"),
                    ("trucker", "trucker"),
                ],
                default="trucker",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CompanyInvitation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
        ),
    ]
