# Generated by Django 5.0.4 on 2024-04-20 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_invitation_user_type_alter_user_user_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="companny",
            new_name="company",
        ),
    ]
