# Generated by Django 5.0.4 on 2024-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_companny_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[("minivan", "minivan"), ("truck", "truck"), ("car", "car")],
                default="car",
                max_length=10,
            ),
        ),
    ]
