# Generated by Django 5.0.4 on 2024-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="current_location",
            field=models.CharField(default="", max_length=100),
        ),
    ]
